### PR TITLE
Updated SocketProvider

### PR DESCRIPTION
**Pull request by joshuacleetus**
Updated socket provider to use socket client to listen to client events like connect, disconnect, error

Allowing the SocketIOClient to be initialized before and passed as a param gives us access to that SocketIOClient for things like listening to connect, disconnect, etc.. This way if there are any errors that happen, we can re-authenticate on Reconnect.

### CODE REVIEW

**Comment by johnjjung** [comment]
@startupthekid @daffl So passing the entire SocketIOClient as the param is very similar to how it's done on the javascript client and we wanted to keep it consistent, please let us know your thoughts

**Comment by thebarndog** [comment]
hmmm @joshuacleetus looks like the travis build failed because of something wrong with the podspec. It might have to do with the swift version, there's been some bugs around that.

I'll try and fix the build, see if I can get it working.

**Comment by joshuacleetus** [comment]
@startupthekid I will update the PR

**Comment by joshuacleetus** [comment]
@startupthekid I made the changes to include SocketManager

**Review by joshuacleetus — COMMENTED** [review]
comment

**Comment by thebarndog** [comment]
The build is still failing @joshuacleetus, I can't merge this until the build is green. You'll have to either merge or rebase `develop`, #7 and #8 will have significant changes.

**Pull request closed without merging**
